version: "3.9"

services:
  api:
    build: .
    image: quemfazniver_api
    container_name: quemfazniver_api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
